import json
import re
from pydantic import BaseModel, Field, ValidationError
from gemini_client import generate_text


class QuizQuestion(BaseModel):
    question: str
    options: list[str] = Field(min_length=4, max_length=4)
    answer: str
    explanation: str


class Quiz(BaseModel):
    questions: list[QuizQuestion] = Field(min_length=3, max_length=3)


def clean_json_block(text: str) -> str:
    text = text.strip()
    text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.IGNORECASE)
    text = re.sub(r"\s*```$", "", text)
    start = text.find("{")
    end = text.rfind("}")
    if start >= 0 and end > start:
        return text[start:end + 1]
    raise ValueError("No JSON object found in model response.")


async def generate_quiz(passage: str) -> dict:
    prompt = f"""
Generate exactly 3 multiple-choice questions from the educational passage below.

Rules:
- Exactly 3 questions.
- Exactly 4 options per question.
- "answer" must exactly match one option.
- Include a concise explanation for the correct answer.
- Questions must be answerable from the passage.
- Return JSON only. No Markdown and no extra commentary.

JSON schema:
{{
  "questions": [
    {{
      "question": "string",
      "options": ["A", "B", "C", "D"],
      "answer": "one of the four options",
      "explanation": "string"
    }}
  ]
}}

PASSAGE:
{passage}
"""
    raw = await generate_text(prompt, temperature=0.2)
    try:
        data = json.loads(clean_json_block(raw))
        quiz = Quiz.model_validate(data)
    except (json.JSONDecodeError, ValueError, ValidationError) as exc:
        raise RuntimeError(f"Could not parse the quiz generated by Gemini: {exc}") from exc

    for q in quiz.questions:
        if q.answer not in q.options:
            raise RuntimeError("Gemini produced a quiz answer that is not one of the options.")

    return quiz.model_dump()
